// packages/adapter-react/src/index.ts
/**
 * @weld/react — useWeld() hook
 *
 * Bridges @weld/core signals to React's rendering cycle
 * using useSyncExternalStore (React 18+). No unnecessary re-renders.
 *
 * Usage:
 *   const { data, status, error } = useWeld(api.get('v1/products', Schema))
 */

import { useSyncExternalStore } from 'react'
import type { WeldResponse, WeldStatus } from '@weld/core'

export interface UseWeldResult<T> {
  data:    T | null
  status:  WeldStatus
  error:   Error | null
  /** True while the request is in-flight */
  loading: boolean
}

/**
 * Subscribes to a WeldResponse and returns reactive state
 * compatible with React's concurrent rendering model.
 *
 * @param response — The WeldResponse returned by api.get() / api.post() / etc.
 */
export function useWeld<T>(response: WeldResponse<T>): UseWeldResult<T> {
  const { signal } = response

  const data = useSyncExternalStore(
    (notify) => signal.data.subscribe(notify),
    () => signal.data.value,
    () => null,
  )

  const status = useSyncExternalStore(
    (notify) => signal.status.subscribe(notify),
    () => signal.status.value,
    () => 'idle' as WeldStatus,
  )

  const error = useSyncExternalStore(
    (notify) => signal.error.subscribe(notify),
    () => signal.error.value,
    () => null,
  )

  return {
    data,
    status,
    error,
    loading: status === 'loading',
  }
}

// packages/adapter-solid/src/index.ts
/**
 * @weld/solid — useWeld() primitive
 *
 * Bridges @weld/core signals to SolidJS's fine-grained reactivity.
 * Since Solid uses signals natively, the bridge is minimal — no overhead.
 *
 * Usage:
 *   const { data, status, error } = useWeld(api.get('v1/products', Schema))
 */

import { createSignal, onCleanup } from 'solid-js'
import type { Accessor }           from 'solid-js'
import type { WeldResponse, WeldStatus } from '@weld/core'

export interface UseWeldResult<T> {
  data:    Accessor<T | null>
  status:  Accessor<WeldStatus>
  error:   Accessor<Error | null>
  loading: Accessor<boolean>
}

/**
 * Subscribes to a WeldResponse and returns SolidJS Accessors.
 * Automatically cleans up when the owner scope is disposed.
 *
 * @param response — The WeldResponse returned by api.get() / api.post() / etc.
 */
export function useWeld<T>(response: WeldResponse<T>): UseWeldResult<T> {
  const { signal } = response

  const [data,   setData]   = createSignal<T | null>(signal.data.value)
  const [status, setStatus] = createSignal<WeldStatus>(signal.status.value)
  const [error,  setError]  = createSignal<Error | null>(signal.error.value)
  const [loading, setLoading] = createSignal<boolean>(signal.status.value === 'loading')

  const unsubData   = signal.data.subscribe((v)   => setData(() => v))
  const unsubStatus = signal.status.subscribe((v) => {
    setStatus(() => v)
    setLoading(v === 'loading')
  })
  const unsubError  = signal.error.subscribe((v)  => setError(() => v))

  onCleanup(() => {
    unsubData()
    unsubStatus()
    unsubError()
  })

  return { data, status, error, loading }
}
